12740 2016-09-22 13:34:56,503  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
12740 2016-09-22 13:35:06,154 127.0.0.1 - - [22/Sep/2016 13:35:06] "GET / HTTP/1.1" 200 -
12740 2016-09-22 13:35:10,605 Processing: cisco
12740 2016-09-22 13:35:10,605 Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\k_zhukov\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask\app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\web.py", line 157, in hello
    for i in table_generate(arr):
  File ".\web.py", line 24, in table_generate
    if all(pn not in i.keys() for i in [data,pid_summary,pid_bad]):
NameError: name 'data' is not defined
12740 2016-09-22 13:35:10,635 127.0.0.1 - - [22/Sep/2016 13:35:10] "POST / HTTP/1.1" 500 -
